{% set name = "c3" %}
{% set version = "0.6.4" %}
{% set sha256 = "0abbccb10bf400bb75df95a3afd281377fbfa81d980c3f00b6a8b5694d05454f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/c3js/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  run:
    - nodejs
    
test:
  commands:
    - npm list -g c3
    

about:
  home: https://github.com/c3js/c3
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A D3-based reusable chart library'
  description: |
    A D3-based reusable chart library   
  doc_url: http://c3js.org/gettingstarted.html
  dev_url: https://github.com/c3js/c3

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
