travis:
  secure:
    BINSTAR_TOKEN: VY60aPB01I3GPChVlDAIVMWw//hb1pKFvjNTB2osC1sEWhVl73RtFg/HQsBmqv5B5y20kZN8/pFPcqJ2LeJ6GMC8KTVL1LcgYWq82fqCpWrwUOvNezVWp44zS3KVMs2UvbGmIIhnd9aIFpDffJ+IzNDEPzFalGIgawTqhxi0IInxCGb+8tc/QXv2ghF63UJbhl/TPMPMidZT2L1zYk6aySXwFCSDS2MgFuTdzyYxSrh2yKoPvnCPa1yrJo8l6RbCR5M6jwdGCxkFb/9gusSGS/eMCN6gT3Lz9Pxep1QVJKtMDK9EScNpn77e76DGFnWLoSUxOqMa7RCQXJ7jh50drjg6UBF6w42MN7e2SK9SFILOyhC0njQsXYJmkgcJAEgMhU3+pBEk9w8vOT2urizmbWwgYQgKKkb8vAkPbqsInuhq31fsZLZzqXMiu+JL3OXBojyBUfJMeOMf/l2DrI7xJlFFuN2PkvGlxs88AQaYClPKMbPxd4kFWLryROfPgZqmd9U2pkrf2h0R4jwz8wKkCeVzZbMwR48dUT6kccoutQoPsuhOHOReC+S7c6UxNc1+m7ZeB1sdJAg7heD+V7ptYzlWfbeatD75l5H9hf/X60UOUQ7NfmCgDH1ttYwjtyEsFbf7FNHVOFUgWp5rGCVAZMcuYQP7w+7FZ6WKYrYItPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
