travis:
  secure:
    BINSTAR_TOKEN: P1vuTn91iJ0FKZujs9m69dS1RxN1gnOKHJ2xaM5T6iiDcWFfJZs6DdbkhbZYc8tKv9oX38vC5zdFxszvxgooKs5qFjOaokH/2iJUjT3RbuWArYhlFScuDjnEjpyFIY5pJJR47jlKvW0bTMWJWHzRFzMRNfLk9Clt/qvflCRbgsr/JRKPJNTc8yegswthZUeIvnNBRzFtJcXolifrUvzTkBxVBtD5aRaun+cE0ti3Q5xhLVefucgRMtJjIBjCFsiEe5PaRddr6bebrPd55Z2MD4BoQLLxRW4+cFUX8JvQVqx8aXcL7rSLddi02Jluetvasn+otpyLg/wScv52Jxsgcbgdi8Rg3QjcH3UhSoOvs9Nf5nWsp+pT/wuRM+DwRkiPMSsrO+qq1aH3cjRYfEVLKEcWQ6+5MgK5466UI67UDUwHYFKvF77MHtx01KlqAYxq3byAto6R3S/0d05fYcDm34mu1r3Gh1u9y0e34fmINQkF6nqKaSNMSXMdyZ4ge2pWFrf1S8j7ZA/WdkNF2+zQNgdF3dEEwDWQFMv6MTy14Eo7ndZh1WPgZJ68JtN4U1KsvWGl0uxiUsluTLtt156IxOfEA5MYkJTOWiMYcBFqTwElitUD8JSTbjRR+o7ahKbaVOauWMsz+CrUv3od1jfspdJwbFym0HFXZm0JUgCja1I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
